<?php
/**
 * @var $block \Payment\Checkout\Block\Adminhtml\Payment\Checkout\Info
 */
?>
<div class="order-payment-method-name"><?= $block->escapeHtml($block->getMethod()->getTitle()); ?></div>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?= $block->escapeHtml(__('Payment Purchase ID')); ?>:</th>
        <td><?= $block->escapeHtml($block->getPaymentPurchaseId()); ?></td>
    </tr>
    <tr>
        <th><?= $block->escapeHtml(__('Payment Payment Method')); ?>:</th>
        <td><?= $block->escapeHtml($block->getPaymentPaymentMethod()); ?></td>
    </tr>
</table>
