<?php
// @codingStandardsIgnoreFile
/** @var \Payment\Checkout\Block\Checkout\Comment $block */
?>
<div id="payment_comment" class="payment-block payment-block-discount">
    <?php $customerComment = $block->getQuote()->getCustomerNote(); ?>
    <form method="post" action="<?= $block->getCommentSubmitUrl(); ?>" id="payment-checkout-comment">
        <div class="payment-comment-title">
            <div class="title-container">
                <h4><?= __('Order Comment (Optionally)')?></h4>
                <input type="button" class="payment-btn show-more" value="<?= __('Show More')?>"/>
                <input type="button" class="payment-btn show-less" value="<?= __('Show Less')?>"/>
            </div>
            <div class="fieldset comment" style="display: none">
                <div class="input-box field">
                <textarea rows="10" value="" placeholder="<?= __('Enter a comment for this order'); ?>"
                          name="payment_customer_comment" id="payment_order_comment_textarea"
                          class="payment-show-on-focus input-text"><?= $customerComment; ?></textarea>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button id="payment-submit" type="submit" title="<?= __('Save'); ?>"
                                class="action apply payment-btn"><?= __('Save'); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
