<?php
// @codingStandardsIgnoreFile
/** @var \Payment\Checkout\Block\Checkout\Shipping $block */
?>

<?php if ($block->getShippingAddress()): ?>
<div class="payment-checkout-shipping payment-checkout-section mobile-show" id="checkout-shipping">
    <div class="checkout-title" data-role="title">
        <h4 id="payment-checkout-review-heading" role="heading" aria-level="2">
            <?= $block->escapeHtml(__('Shipping Method')) ?>
        </h4>
    </div>
    <div class="payment-checkout-section-content" data-role="content"
         aria-labelledby="payment-checkout-review-heading">
        <form method="post" id="shipping-method-form"
              action="<?= $block->escapeUrl($block->getShippingMethodSubmitUrl()); ?>"
              class="form">
            <?= $block->getChildHtml('shipping_method'); ?>
        </form>
        <?php if ($addrUrl = $block->getShippingAddressSubmitUrl()): ?>
            <?= $block->getChildHtml('shipping_address'); ?>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
