<?php

// @codingStandardsIgnoreFile
/** @var $block \Payment\Checkout\Block\Checkout */

//id  #payment-checkout_shipping_method is mandatory

?>
<div id="payment-checkout_shipping_method">
    <div class="shipping-method-holder" >
        <?php if ($groups = $block->getShippingRateGroups()): ?>
            <?php $currentRate = $block->getCurrentShippingRate(); ?>
            <?php foreach ($groups as $code => $rates): ?>
                <?php if (0): ?><strong><?php echo $block->escapeHtml($block->getCarrierName($code)) ?></strong><?php endif; ?>
                <?php foreach ($rates as $rate):
                    $value = $block->escapeHtml($block->renderShippingRateValue($rate));
                    $checked = $currentRate === $rate->getCode() ? 'checked' : '';
                    ?>
                    <div class="payment-checkout-radio-row">
                        <span>
                            <input type="radio"
                                   name="shipping_method" <?php echo $checked; ?> value="<?= $value; ?>"
                                   id="<?php echo $value; ?>">
                            <label for="<?php echo $value; ?>">
                                <?= $block->renderShippingRateOption($rate); ?>
                            </label>
                        </span>
                    </div>
                <?php endforeach; ?>
            <?php endforeach; ?>

        <?php else: ?>
            <p>
                <strong>
                    <?= $block->escapeHtml(__('Sorry, no quotes are available for this order right now.')); ?>
                </strong>
            </p>
        <?php endif; ?>
    </div>
</div>
